### ISSUE TITLE
Document Release Processes

### ISSUE THREAD

**Issue by nathancolgate** [brandnewbox/bnb_blazer#10]
> We'll need to cut a new release to Ruby Gems to get this added to a project. - @willtcarey in #7 

Let's document this.

**Comment by willtcarey** [comment]
Step 1 here is setting up a BNB RubyGems account (I can tackle that) as the gem currently lives under Joe's RubyGems account

**Comment by ashleyHutton** [comment]
To release a new version of the BNB blazer gem:

1. Clone the project and make your changes
2. Bump the version in `version.rb`.
4. Build the gem: `gem build bnb_blazer.gemspec`. This will create a `bnb-blazer-[version].gem`
5. If you aren't already: Make sure you are an owner of the [bnb_blazer gem](https://rubygems.org/gems/bnb_blazer). An existing owner can add you: `gem owner bnb_blazer --add yourname@brandnewbox.com`
6. If you don't have one already: Create a [RubyGems account](https://rubygems.org/) with your BNB email
7. If you haven't already: login to RubyGems in your terminal: `gem signin`
8. Push the gem: `gem push bnb-blazer-[version].gem`
9. You should see the new version [here](https://rubygems.org/gems/bnb_blazer)


More info about the RubyGems build/release process is [here](https://guides.rubygems.org/make-your-own-gem/).
