### ISSUE TITLE
Support blazer > v2.4

### ISSUE THREAD

**Issue by ashleyHutton** [brandnewbox/bnb_blazer#14]
This gem [breaks](https://github.com/brandnewbox/ksdetasn/issues/1111) when the installed blazer gem is > v2.4 (specifically v2.6.4). There a quite a few changes in the views between those versions.

**Comment by willtcarey** [comment]
This is handled in the latest release https://github.com/brandnewbox/bnb_blazer/releases/tag/v0.14.0
