### ISSUE TITLE
Not Escaping HTML

### ISSUE THREAD

**Issue by mwilkins74** [brandnewbox/bnb_blazer#15]
While working on CPPR  https://github.com/brandnewbox/cppr-institute/issues/806 I ran into this problem when running queries in Blazer. 

I was working Ruby 2.6.6 and Rails 6.

<img width="1300" alt="Screen Shot 2023-02-10 at 3 59 24 PM" src="https://user-images.githubusercontent.com/102488171/218196382-571ce51d-ae22-4deb-ae35-bc5d1fe83e3a.png">

**Comment by willtcarey** [comment]
This wound up being related to the `turbolinks_render` gem which takes over the rendering pipeline for turbolinks requests. Blazer isn't expecting this so we need to ignore the blazer path which resulted in this commit https://github.com/brandnewbox/cppr-institute/pull/810/commits/e8dbfab51d79f0e9baf84bf14d9a5d52c50a7c95.
