### ISSUE TITLE
Security Updates

### ISSUE THREAD

**Issue by nathancolgate** [brandnewbox/bnb_blazer#19]
There are a pile of them here, and updates may be done automatically? Not 100% sure.

https://github.com/brandnewbox/bnb_blazer/security/dependabot?q=is%3Aopen+manifest%3AGemfile.lock+package%3Anokogiri

**Comment by willtcarey** [comment]
Usually it makes a PR for us. Not sure why it didn't on this one. Looks like we need a nokogiri update to fix these though

**Comment by JaceBayless** [comment]
I tried clicking the button to automatically generate the update but it errored for both the `actionpack` issues and the `nokogiri` issues. Probably will have to manually update this.
