### ISSUE TITLE
Put BNBintel onto updates so we can dogfood it

### ISSUE THREAD

**Issue by mattkirkland** [brandnewbox/bnb_blazer#28]
The only branded version of this is on the Institute. But they are careful about their platform, and I'd like to have a version of this that we can mess with a bit more freely. And mess with = just USE; write queries, etc. 

So: let's out this into BNB updates.

**Comment by willtcarey** [comment]
Let's install BNBintel from the `master` branch here so that it's easier to update and try out changes
