### ISSUE TITLE
Figure Out How "Gem-Wrappers" Work

### ISSUE THREAD

**Issue by PickertJoe** [brandnewbox/bnb_blazer#3]
- How do we inherit from another gem?
- How do we override the views on that gem?

**Comment by nathancolgate** [comment]
Quick / vague thoughts to get you pointed in the right direction.

* Rails maintains a list of [paths to look for views](https://api.rubyonrails.org/classes/ActionView/ViewPaths.html#method-i-prepend_view_path).
* At it's most basic, it looks like `["/app/views"]`
* When you install a gem, like devise, it uses `append_view_path` to become something like `["/app/views","gems/devise/app/views"]`
* So, if you say `render template: 'registrations/new` it _first_ looks in `/app/views`.
* If it finds it (i.e. you've provided a custom view for the gem) it uses it.
* If it doesn't find it, it moves to the next item in the list and looks there (i.e. the default view provided by the gem)
* And so on.
* If it reaches the end of the list, it raises "Template not found"

So what you'll want to do in the `bnb-blazer` gem is figure out how to modify that list so it looks like:

```
["/app/views","gems/bnb-blazer/app/views","gems/blazer/app/views"]
```

That would:

* provide users the option to override the view in their app locally if they want
* fall back to views in `bnb-blazer` (our customization!)
* fall back to [view](https://github.com/ankane/blazer/tree/master/app/views) in `blazer` (if there is anything we want to leave as-is)
