### ISSUE TITLE
add some first-round custom styling

### ISSUE THREAD

**Issue by mattkirkland** [brandnewbox/bnb_blazer#6]
See these early mocks; could we start laying in some basic styling to make this more BNB-like?

Example Report:

![example_report_Tablet](https://user-images.githubusercontent.com/714254/129078210-35370361-3a60-450d-80de-cd623379cc8a.png)

Example Report mobile:

![example_report_Mobile1](https://user-images.githubusercontent.com/714254/129078222-363d604b-1464-42a0-b022-66e2fbd0b3a4.png)

Example Sidebar nav for mobile views
![mobile_nav](https://user-images.githubusercontent.com/714254/129078228-6393d848-25d2-4ce2-a3bd-d07c4fc8dc63.png)

**Comment by willtcarey** [comment]
I started work on this in the `styling` branch

**Comment by willtcarey** [comment]
Progress is coming along nicely!

![localhost_3000_blazer_](https://user-images.githubusercontent.com/880387/130812199-167c2b19-13cb-465a-a095-cd9b05f9cc27.png)
![localhost_3000_blazer_queries_1-credit-score-scatter-plot](https://user-images.githubusercontent.com/880387/130812208-f9589b2a-9a30-40e0-8b03-c7131b6a6654.png)

**Comment by mattkirkland** [comment]
exciting!

**Comment by willtcarey** [comment]
My WIP is on the `styling` branch. I was in the middle of doing the sidebar for this.
