### ISSUE TITLE
deploy this to a client site to start dogfooding

### ISSUE THREAD

**Issue by mattkirkland** [brandnewbox/bnb_blazer#7]

**Comment by opticbob** [comment]
@mattkirkland Right now the gem still looks like the base blazer gem.  Do we want to deploy it before we have custom styling?

**Comment by opticbob** [comment]
@mattkirkland I was going to add this to ksdetasn but I'm holding for now.

**Comment by mattkirkland** [comment]
Yeah, agreed, this really should happen after #6 is complete

**Comment by opticbob** [comment]
The work for this issue is in brandnewbox/ksdetasn#765.

**Comment by willtcarey** [comment]
We'll need to cut a new release to Ruby Gems to get this added to a project.

**Comment by nathancolgate** [comment]
If someone knows how to release this gem, they should tackle this and #10 simultaneously.

**Comment by ashleyHutton** [comment]
This is deployed in tasn https://www.ksdetasn.org/blazer.
